[package]
name = "safe-client-gateway"
version = "3.0.0"
authors = ["jpalvarezl <jose.alvarez@gnosis.io>", "rmeissner <richard@gnosis.io>", "fmrsabino <frederico@gnosis.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"

regex = "1.4.6"
lazy_static = "1.4.0"

rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "dd9629697a3cbe45f50645579f41f1a957a92968", features = ["tls", "json"] }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket", rev = "dd9629697a3cbe45f50645579f41f1a957a92968" }

# Force rocket peer-dependencies versions
proc-macro2 = "1.0.28"
tokio = "1.6.1"

reqwest = { version = "0.11.3", features = ["json"] }

r2d2 = "0.8.9"
redis = { version = "0.20", features = ["r2d2"] }

ethcontract-common = "0.11.1"
ethereum-types = { version = "0.10.0", features = ["serialize"] }
ethabi = "12.0.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"

itertools = "0.9.0"

derivative = "2.2.0"

chrono = { version = "0.4", features = ["serde"] }

thiserror = "1.0.20"

mockall = "0.9.1"

semver = "0.11.0"

# Logging
log = "0.4"
env_logger = "0.9.0"

[dev-dependencies]
cargo-watch = "7.6.1"
